version:  '3.8'

services:
  mongo:
    build:
      dockerfile: Dockerfile
      context: "./db"
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always

  api:
    build:
      dockerfile: Dockerfile
      context: "./api"
    ports:
      - "4002:4002"
    depends_on:
      - mongo
    environment:
      - DB=mongodb://mongo:27017/
      - PORT=4002
  app:
    build:
      dockerfile: Dockerfile
      context: "./app"
    ports:
      - "3010:3010"
    depends_on:
      - mongo
      - api
    environment:
      - PORT=3010